
version: '3'

services:
    zookeeper:
        container_name: zookeeper
        image: confluentinc/cp-zookeeper:7.4.3
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
    kafka:
        container_name: kafka
        image: confluentinc/cp-kafka:7.4.3
        ports:
            - "49092:49092"
        depends_on:
            - zookeeper
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:49092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    kafka-ui:
        container_name: kafka-ui
        image: ghcr.io/kafbat/kafka-ui:latest
        ports:
            - "10015:8080"
        depends_on:
            - kafka
        environment:
            KAFKA_CLUSTERS_0_NAME: local
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    kinetiq:
        container_name: kinetiq
        build:
            dockerfile: Dockerfile
            context: .
        ports:
            - "8080:8080"
        environment:
            KAFKA_SOURCE_TOPIC: kinetiq-test-topic
            KAFKA_DEST_TOPIC: kinetiq-test-topic-out
            KAFKA_SOURCE_BROKERS: kafka:9092
            PLUGIN_REF: ./examples/test_module/test_module.wasm
        volumes:
            - ./examples/test_module_complex/test_module.wasm:/root/examples/test_module/test_module.wasm:ro
        depends_on:
            - kafka
