version: '3.8'

services:
  kafka1:
    image: apache/kafka:latest
    container_name: kafka1
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_LISTENERS: "SASL_SSL://0.0.0.0:9092,CONTROLLER://kafka1:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_ADVERTISED_LISTENERS: "SASL_SSL://kafka1:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "SASL_SSL:SASL_SSL,CONTROLLER:SASL_SSL"
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_SSL
      KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-512
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SCRAM-SHA-512
      KAFKA_SASL_MECHANISM_CONTROLLER: SCRAM-SHA-512
      KAFKA_SUPER_USERS: "User:admin"
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/secrets/kafka_server_jaas.conf"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"
      KAFKA_SSL_KEYSTORE_FILENAME: "kafka.keystore.jks"
      KAFKA_SSL_KEYSTORE_CREDENTIALS: "pass"
      KAFKA_SSL_KEY_CREDENTIALS: "pass"
      KAFKA_SSL_TRUSTSTORE_FILENAME: "kafka.truststore.jks"
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: "pass"
    volumes:
      - ./secrets:/etc/kafka/secrets

  kafka2:
    image: apache/kafka:latest
    container_name: kafka2
    restart: always
    ports:
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_LISTENERS: "SASL_SSL://0.0.0.0:9093,CONTROLLER://kafka2:9094"
      KAFKA_ADVERTISED_LISTENERS: "SASL_SSL://kafka2:9093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "SASL_SSL:SASL_SSL,CONTROLLER:SASL_SSL"
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_SSL
      KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-512
      KAFKA_SASL_MECHANISM_CONTROLLER: SCRAM-SHA-512
      KAFKA_SUPER_USERS: "User:admin"
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/secrets/kafka_server_jaas.conf"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"
      KAFKA_SSL_KEYSTORE_LOCATION: "/etc/kafka/secrets/kafka.keystore.jks"
      KAFKA_SSL_KEYSTORE_PASSWORD: "changeit"
      KAFKA_SSL_TRUSTSTORE_LOCATION: "/etc/kafka/secrets/kafka.truststore.jks"
      KAFKA_SSL_TRUSTSTORE_PASSWORD: "changeit"
    volumes:
      - ./secrets:/etc/kafka/secrets

  kafka3:
    image: apache/kafka:latest
    container_name: kafka3
    restart: always
    ports:
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_LISTENERS: "SASL_SSL://0.0.0.0:9094,CONTROLLER://kafka3:9095"
      KAFKA_ADVERTISED_LISTENERS: "SASL_SSL://kafka3:9094"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "SASL_SSL:SASL_SSL,CONTROLLER:SASL_SSL"
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_SSL
      KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-512
      KAFKA_SASL_MECHANISM_CONTROLLER: SCRAM-SHA-512
      KAFKA_SUPER_USERS: "User:admin"
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/secrets/kafka_server_jaas.conf"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"
      KAFKA_SSL_KEYSTORE_LOCATION: "/etc/kafka/secrets/kafka.keystore.jks"
      KAFKA_SSL_KEYSTORE_PASSWORD: "changeit"
      KAFKA_SSL_TRUSTSTORE_LOCATION: "/etc/kafka/secrets/kafka.truststore.jks"
      KAFKA_SSL_TRUSTSTORE_PASSWORD: "changeit"
    volumes:
      - ./secrets:/etc/kafka/secrets

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    container_name: schema-registry
    restart: always
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "SASL_SSL://kafka1:9092,SASL_SSL://kafka2:9093,SASL_SSL://kafka3:9094"
      SCHEMA_REGISTRY_HOST_NAME: "schema-registry"
      SCHEMA_REGISTRY_LISTENERS: "https://0.0.0.0:8081"
      SCHEMA_REGISTRY_SSL_TRUSTSTORE_LOCATION: "/etc/kafka/secrets/kafka.truststore.jks"
      SCHEMA_REGISTRY_SSL_TRUSTSTORE_PASSWORD: "changeit"
      SCHEMA_REGISTRY_OPTS: "-Djava.security.auth.login.config=/etc/kafka/secrets/kafka_client_jaas.conf"
    volumes:
      - ./secrets:/etc/kafka/secrets

  kafbat:
    image: kafbat/kafka-ui:latest
    container_name: kafka-ui
    restart: always
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - schema-registry
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "KafkaCluster"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "SASL_SSL://kafka1:9092,SASL_SSL://kafka2:9093,SASL_SSL://kafka3:9094"
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: "https://schema-registry:8081"
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: "SCRAM-SHA-512"
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: "SASL_SSL"
    volumes:
      - ./secrets:/etc/kafka/secrets
      - ./secrets/kafbat-config.yaml:/etc/kafbat/application.yml:ro

  cruise-control:
    image: adobe/cruise-control:latest
    container_name: cruise-control
    restart: always
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    ports:
      - "9090:9090"
    environment:
      CRUISE_CONTROL_BOOTSTRAP_SERVERS: "SASL_SSL://kafka1:9092,SASL_SSL://kafka2:9093,SASL_SSL://kafka3:9094"
      CRUISE_CONTROL_SECURITY_PROTOCOL: "SASL_SSL"
      CRUISE_CONTROL_SASL_MECHANISM: "SCRAM-SHA-512"
      CRUISE_CONTROL_SASL_USERNAME: "admin"
      CRUISE_CONTROL_SASL_PASSWORD: "admin-secret"
    volumes:
      - ./secrets:/etc/kafka/secrets