receivers:
    otlp:
        protocols:
            grpc:

processors:
    batch:

exporters:
    debug:
    prometheus:
        endpoint: "0.0.0.0:8889"
        namespace: default
    otlp:
        endpoint: jaeger:14317
        tls:
            insecure: true
        timeout: 10s
    loki:
        endpoint: "http://loki:3100/loki/api/v1/push"

extensions:
    health_check:
    pprof:
    zpages:

service:
    extensions: [health_check, pprof, zpages]
    pipelines:
        traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [debug, otlp]
        metrics:
            receivers: [otlp]
            processors: [batch]
            exporters: [debug, prometheus]
        logs:
            receivers: [otlp]
            processors: [batch]
            exporters: [debug, loki]
