// Code generated by mockery v2.52.2. DO NOT EDIT.

package functions

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockHttpClient is an autogenerated mock type for the HttpClient type
type MockHttpClient struct {
	mock.Mock
}

type MockHttpClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHttpClient) EXPECT() *MockHttpClient_Expecter {
	return &MockHttpClient_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: url
func (_m *MockHttpClient) Get(url string) (*http.Response, error) {
	ret := _m.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*http.Response, error)); ok {
		return rf(url)
	}
	if rf, ok := ret.Get(0).(func(string) *http.Response); ok {
		r0 = rf(url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHttpClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockHttpClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - url string
func (_e *MockHttpClient_Expecter) Get(url interface{}) *MockHttpClient_Get_Call {
	return &MockHttpClient_Get_Call{Call: _e.mock.On("Get", url)}
}

func (_c *MockHttpClient_Get_Call) Run(run func(url string)) *MockHttpClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockHttpClient_Get_Call) Return(_a0 *http.Response, _a1 error) *MockHttpClient_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHttpClient_Get_Call) RunAndReturn(run func(string) (*http.Response, error)) *MockHttpClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHttpClient creates a new instance of MockHttpClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHttpClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHttpClient {
	mock := &MockHttpClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
