// Code generated by mockery v2.52.2. DO NOT EDIT.

package detection

import mock "github.com/stretchr/testify/mock"

// MockDetectable is an autogenerated mock type for the Detectable type
type MockDetectable struct {
	mock.Mock
}

type MockDetectable_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDetectable) EXPECT() *MockDetectable_Expecter {
	return &MockDetectable_Expecter{mock: &_m.Mock}
}

// NewMockDetectable creates a new instance of MockDetectable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDetectable(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDetectable {
	mock := &MockDetectable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
