name: Feature Branch Build
on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Unit Tests
        run: go test ./...
      - name: Build and Push Image
        uses: ./.github/workflows/docker-publish.yml
        with:
          tag: ${{ github.sha }}