name: Feature Branch Build
on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Unit Tests
        run: go test ./...

      - name: Build and Push Image
        uses: ./.github/actions/docker-publish/action.yml
        with:
          tag: ${{ github.sha }}
        secrets:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}