name: Feature Branch Build
on:
  push:
    branches-ignore:
      - main

jobs:
  build-and-push:
    uses: .github/workflows/docker-publish.yml@feat/dockerizification
    with:
      docker-owner: 'paintface07'
      tags: ${{ env.GITHUB_SHA }}
    secrets: inherit