name: Feature Branch Build
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'         # vX.X.X
      - 'v[0-9]+.[0-9]+.[0-9]+-(rc|beta|alpha).[0-9]+' # vX.X.X-rc.N | vX.X.X-alpha.N | vX.X.X-beta.N


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Extract version from tag
        run: |
          VERSION=${GITHUB_REF_NAME#v}  # Remove 'v' prefix
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and Push Image
        uses: ./.github/workflows/docker-publish.yml
        with:
          tag: $VERSION